from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

SPLITS_DIR = PROCESSED_DATA_DIR / "splits"
PREPROCESSED_DATA_DIR = PROCESSED_DATA_DIR / "preprocessed"

RESULTS_DIR = PROJECT_ROOT / "results"
MODELS_DIR = PROJECT_ROOT / "models"

ADULT_ARFF_PATH = RAW_DATA_DIR / "adult.arff"

TARGET_COLUMN = "income"

TEST_SIZE = 0.20

RANDOM_SEEDS = [42, 123, 2026]

# GAN training configuration
GAN_LATENT_DIM = 64
GAN_BATCH_SIZE = 256
GAN_EPOCHS = 300
GAN_LEARNING_RATE = 0.0002
GAN_BETA1 = 0.5
GAN_BETA2 = 0.999
GAN_PRINT_EVERY = 10

# cGAN training configuration
CGAN_LATENT_DIM = 64
CGAN_BATCH_SIZE = 256
CGAN_EPOCHS = 300
CGAN_LEARNING_RATE = 0.0002
CGAN_BETA1 = 0.5
CGAN_BETA2 = 0.999
CGAN_PRINT_EVERY = 10

# Evaluation configuration
EVALUATION_RF_N_ESTIMATORS = 200
EVALUATION_RF_MAX_DEPTH = None
EVALUATION_RF_N_JOBS = -1
EVALUATION_NUM_FOLDS = 4

# Discrete categorical generation experiments
DISCRETE_EXPERIMENT_SEED = 42
DISCRETE_GAN_EPOCHS = 300
DISCRETE_GAN_LATENT_DIM = 64
DISCRETE_GAN_BATCH_SIZE = 256
DISCRETE_GAN_LEARNING_RATE = 0.0002
DISCRETE_GAN_BETA1 = 0.5
DISCRETE_GAN_BETA2 = 0.999
DISCRETE_GAN_PRINT_EVERY = 10
GUMBEL_TAU = 0.7

# Mode collapse experiments
MODE_COLLAPSE_SEED = 42
MODE_COLLAPSE_EPOCHS = 150
MODE_COLLAPSE_BATCH_SIZE = 256
MODE_COLLAPSE_LEARNING_RATE = 0.0002
MODE_COLLAPSE_BETA1 = 0.5
MODE_COLLAPSE_BETA2 = 0.999
MODE_COLLAPSE_PRINT_EVERY = 10

COLLAPSED_LATENT_DIM = 4
COLLAPSED_GENERATOR_HIDDEN_DIMS = (32,)
COLLAPSED_DISCRIMINATOR_HIDDEN_DIMS = (256, 128, 64)
COLLAPSED_D_UPDATES_PER_G_UPDATE = 5

MITIGATION_DIVERSITY_WEIGHT = 0.5

# Open-ended contribution: Feature Matching GAN
OPEN_ENDED_SEED = 42
OPEN_ENDED_LATENT_DIM = 64
OPEN_ENDED_BATCH_SIZE = 256
OPEN_ENDED_EPOCHS = 300
OPEN_ENDED_LEARNING_RATE = 0.0002
OPEN_ENDED_BETA1 = 0.5
OPEN_ENDED_BETA2 = 0.999
OPEN_ENDED_PRINT_EVERY = 10
FEATURE_MATCHING_WEIGHT = 10.0