import numpy as np

def linear_backward(dZ, cache):
    """
    linear part of the backward propagation process for a single layer
    
    Args:
        dZ (vector): Gradient of the cost with respect to the linear output (of current layer l)
        cache (tuple): tuple of values (A_prev, W, b) coming from the forward propagation in the current layer
        
    Returns:
        dA_prev (vector): Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
        dW (matrix): Gradient of the cost with respect to W (current layer l), same shape as W
        db (vector): Gradient of the cost with respect to b (current layer l), same shape as b
    """
    
    A_prev, W, b = cache
    m = A_prev.shape[1]  # Number of examples in the batch
    
    dW = (1 / m) * np.dot(dZ, A_prev.T) # Compute the gradient with respect to W
    db = (1 / m) * np.sum(dZ, axis=1, keepdims=True) # Compute the gradient with respect to b
    dA_prev = np.dot(W.T, dZ) # Compute the gradient with respect to the activation of the previous layer
    
    return dA_prev, dW, db
    
    
    
    
def linear_activation_backward(dA, cache, activation):
    """
    Backward propagation for the LINEAR->ACTIVATION layer
    
    Args:
        dA (vector): post-activation gradient for current layer l
        cache (tuple): tuple contains both the linear cache and the activation cache
        
    Returns:
        dA_prev (vector): Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
        dW (matrix): Gradient of the cost with respect to W (current layer l), same shape as W
        db (vector): Gradient of the cost with respect to b (current layer l), same shape as b
    """
    
    
def relu_backward(dA, activation_cache):
    """
    Backward propagation for a single RELU unit
    
    Args:
        dA (vector): post-activation gradient for current layer l
        activation_cache (vector): cache containing Z (stored in forward) for backpropagation
        
    Returns:
        dZ : gradient of the cost with respect to Z 
    """
    
    
def softmax_backward (dA, activation_cache):
    """
    Backward propagation for a softmax unit
    
    Args:
        dA (vector): post-activation gradient for current layer l
        activation_cache (vector): cache containing Z (stored in forward) for backpropagation
        
    Returns:
        dZ : gradient of the cost with respect to Z 
    """
    
    
def l_model_backward(AL, Y, caches):
    """
    Backward propagation process for the entire network
    
    Args:
        AL (vector): probabilities vector, the output of the forward propagation (L_model_forward)
        Y (vector): the true labels vector
        caches (list): list of caches containing for each layer: a) the linear cache; b) the activation cache
        
    Returns:
        Grads (dictionary): A dictionary with the gradients
                     grads["dA" + str(l)] = ... 
                     grads["dW" + str(l)] = ...
                     grads["db" + str(l)] = ...
    """
    
    
def update_parameters(parameters, grads, learning_rate):
    """
    Updates parameters using gradient descent
    
    Args:
        parameters (dictionary): containing the DNN architectures parameters
        grads (dictionary): containing the gradients (generated by L_model_backward)
        learning_rate (float): the learning rate used to update the parameters (the “alpha”)
        
    Returns:
        parameters : the updated values of the parameters object provided as input
    """