import numpy as np


def initialize_parameters(layer_dims):
    """
    Initialize parameters for a fully connected neural network
    
    Args:
        layer_dims (list): dimensions of each layer in the network.
    Returns:
        dict: dictionary containing initialized weights and biases
        keys: W1, W2,..., WL for weights and b1, b2,..., bL for biases
        values: the weights and the biases
    """
    
    np.random.seed(42)
    parameters = {}
    L = len(layer_dims)
    
    for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * np.sqrt(2 / layer_dims[l-1])  # Initialization the weights
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))  # Initialization the bias
        
    return parameters
    
    
def linear_forward(A, W, b):
    """
    Compute the linear part of the forward propagation
    
    Args:
        A (matrix): the activations of the previous layer
        W (matrix): the weight matrix of the current layer
        b (vector): the bias vector of the current layer

    Returns:
        Z (vector): linear component of the activation function
        linear_cache (tuple): cache containing A, W, b for backpropagation
    """

    if W.shape[1] != A.shape[0]:
        raise ValueError("Incompatible dimensions in linear_forward")  # Check if the dimensions are compatible for matrix multiplication
    Z = np.dot(W, A) + b   # Compute the linear part of the forward propagation
    return Z, (A, W, b)
    

def softmax(Z):
    """
    Compute the softmax activation function
    
    Args:
        Z (vector): linear component of the activation function
        
    Returns:
        A (vector): activations of the layer
        activations_cache (vector): cache containing Z for backpropagation
    """
    shifted_Z = Z - np.max(Z, axis=0, keepdims=True)  # Shift Z for numerical stability -> for long numbers, we wont get overflow
    exp_z = np.exp(shifted_Z)  # Compute the exponential of each element in shifted_Z
    sum_exp_z = np.sum(exp_z, axis=0, keepdims=True)  # Compute the sum of the exponentials
    A = exp_z / sum_exp_z  # Compute the softmax output
    activations_cache = Z
    return A, activations_cache
    
    
def relu(Z):
    """
    Compute the ReLU activation function
    
    Args:
        Z (vector): linear component of the activation function
        
    Returns:
        A (vector): activations of the layer
        activations_cache (vector): cache containing Z for backpropagation
    """
    A = np.maximum(0, Z)  # Apply ReLU activation function -> for each dimension, if Z is greater than 0, keep it; otherwise, set it to 0
    activations_cache = Z
    return A, activations_cache
    

def linear_activation_forward(A_prev, W, B, activation):
    """
    Compute the forward propagation for the LINEAR->ACTIVATION layer
    
    Args:
        A_prev (vector): activations of the previous layer
        W (matrix): weights matrix of the current layer
        B (vector):  bias vector of the current layer
        activation (string): activation function to be used in this layer, "relu" or "softmax"
        
    Returns:
        A (vector): activations of the current layer
        cache (dictionary): joint dictionary containing both linear_cache and activation_cache

    """
    Z, linear_cache = linear_forward(A_prev, W, B)  # Compute the linear part of the forward propagation
    
    A, activation_cache = softmax(Z) if activation == "softmax" else relu(Z)  # Compute the activation function

    #cache = (linear_cache, activation_cache)  # Cache for the entire layer
    cache = {
        "linear_cache": linear_cache,
        "activation_cache": activation_cache
    }
    return A, cache
    
    
def l_model_forward(X, parameters, use_batchnorm):
    """
    forward propagation for the [LINEAR->RELU]*(L-1)->LINEAR->SOFTMAX computation

    Args:
        X (_type_): the data, numpy array of shape (input size, number of examples)
        parameters: the initialized W and b parameters of each layer
        use_batchnorm (boolean): boolean flag used to determine whether to apply batchnorm after the activation
        
    Returns:
        AL - the last post-activation value
        caches - a list of all the cache objects generated by the linear_forward function
    """
    
    caches = []
    A = X
    L = len(parameters) // 2  # Number of layers in the neural network
    
    # Hidden layers with ReLU activation
    for l in range(1, L):
        A_prev = A
        cur_W = parameters["W" + str(l)]
        cur_b = parameters["b" + str(l)]
        
        A, cache = linear_activation_forward(A_prev, cur_W, cur_b, activation="relu")  # Compute the forward propagation for the current layer
        
        if use_batchnorm:
            A = apply_batchnorm(A)
            
        caches.append(cache)
    
    
    # Last layer with softmax activation
    last_W = parameters[f'W{L}']
    last_b = parameters[f'b{L}']
    AL, cache = linear_activation_forward(A, last_W, last_b, activation="softmax")  # Compute the forward propagation for the last layer
    caches.append(cache)
    
    return AL, caches
    
    
def compute_cost(AL, Y, parameters=None,l2_lambda=0.0):
    """
    Implementation of a cost function, in this case -> cross-entropy loss

    Args:
        AL (vector): probability vector
        Y (vector): labels
        l2_lambda (float): regularization parameter for L2 regularization (default is 0, meaning no regularization)
        
    Returns:
        cost (float): cross-entropy cost
    """
    
    num_classes, m = Y.shape[0], Y.shape[1]  # Number of examples
    cost_sum = 0.0
    
    for i in range(m):
        for j in range(num_classes):
            al_value = AL[j][i] if AL[j][i] >= 1e-12 else 1e-12  # Avoid log(0) by adding a small constant
            cost_sum += Y[j][i] * np.log(al_value)
            
    cross_entropy_cost = -(1 / m) * cost_sum  # Compute the average cost over all examples
    
    # L2 regularization cost
    l2_cost = 0.0
    if parameters is not None and l2_lambda > 0:
        L = len(parameters) // 2  # Number of layers in the network
        weights_squared_sum = 0.0
        
        for l in range(1, L + 1):
            W = parameters["W" + str(l)]
            weights_squared_sum += np.sum(W ** 2)  # Sum of squares of the weights
            
        l2_cost = (l2_lambda / (2 * m)) * weights_squared_sum  # Compute the L2 regularization cost
        
    cost = cross_entropy_cost + l2_cost  # Total cost is the sum of cross-entropy cost and L2 regularization cost
    return cost

    
def apply_batchnorm(A):
    """
    batchnorm on the received activation values of a given layer

    Args:
        A (vector): activation values of a given layer
        
    Returns:
        NA (vector): normalized activation values
    """
    epsilon = 1e-8  # Small constant to prevent division by zero
    
    mean_A = np.mean(A, axis=1, keepdims=True)  # Compute the mean of A
    variance_A = np.var(A, axis=1, keepdims=True)  # Compute the variance of A
    
    NA = (A - mean_A) / np.sqrt(variance_A + epsilon)  # Normalize A using the mean and variance
    return NA



# def calculate_matrix_mean(A):
#     """

#     Args:
#         A (_type_): _description_
#     """
    
#     num_units = A.shape[0]
#     m = A.shape[1]
    